### ISSUE TITLE
Could not intialize container! when trying to use "guitar.ogg" as Main Audio

### ISSUE THREAD

**Issue by DerReparator** [iminashi/Rocksmith2014.NET#10]
Hi,
I tried creating my first CDLC today but when I tried to set EOF's exported _guitar.ogg_ as the Main Audio of my song I got the following error message:

```
ArgumentException: Could not initialize container!
   at NAudio.Vorbis.VorbisSampleProvider..ctor(Stream sourceStream, Boolean closeOnDispose)
   at NAudio.Vorbis.VorbisWaveReader..ctor(Stream sourceStream, Boolean closeOnDispose)
   at NAudio.Vorbis.VorbisWaveReader..ctor(String fileName)
   at Rocksmith2014.Audio.Types.AudioReader.Create(String fileName)
   at Rocksmith2014.Audio.Volume.calculate(String fileName)
   at DLCBuilder.Main.task@310-36.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```

My original song (also in *.ogg) could be set without issues and a preview.ogg I created and exported in EOF also worked without issue.

Can someone provide information regarding this error?

**Comment by iminashi** [comment]
This appears t be a bug in the vorbis library used.

As a workaround you can use the wav file created by EOF, or re-encoding the file as ogg in a program like Audacity should also work.

**Comment by DerReparator** [comment]
Yes, that worked for me - thank you!
Do you think this issue should be communicated to the EOF development team?

**Comment by iminashi** [comment]
It's not an issue in EOF itself, since EOF relies on external tools for working with ogg files.

I've opened an [issue in NVorbis](https://github.com/NVorbis/NVorbis/issues/20).

**Comment by DerReparator** [comment]
Alright! Thank you
