### ISSUE TITLE
Crash on Import PSARC File (Quick Edit)

### ISSUE THREAD

**Issue by pavianshupe** [iminashi/Rocksmith2014.NET#19]
DLC Builder 2.2.2 crashes on Mac Air M2 (Ventura 13.5) when opening Mac PSARC for quick edit with following message:

AggregateException: One or more errors occurred. (revorb process failed with exit code: 134)

Inner exception:
Exception: revorb process failed with exit code: 134
   at Rocksmith2014.Audio.Conversion.validateRevorbOutput(Int32 exitCode, String output)
   at Rocksmith2014.Audio.Conversion.wemToOggImpl(String sourcePath, String targetPath)
   at Rocksmith2014.Audio.Conversion.wemToOgg(String wemFile)
   at DLCBuilder.Utils.convert@220.Invoke(String wemFile)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 632
   at DLCBuilder.StateUtils.importPsarc@416.MoveNext()
   at DLCBuilder.Main.task@220-28.MoveNext()

**Comment by iminashi** [comment]
I wonder if it's somehow related to the issue on linux #15?

Don't know if rebuilding [revorb](https://github.com/jonboydell/revorb-nix) would help.
